Lesson 7

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
b = ((zp * ks).mean() - zp.mean() * ks.mean()) / ((zp ** 2).mean() - (zp.mean() ** 2))
a = ks.mean() - b * zp.mean()
mse = np.sum(((a + b * zp) - ks) ** 2 / 10)
b,a,mse, zp

(2.620538882402765,
 444.1773573243596,
 6470.414201176659,
 array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]))

C интерсепт

In [27]:
zp1 = np.vstack([np.ones((1, 10)), zp])

array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [ 35.,  45., 190., 200.,  40.,  70.,  54., 150., 120., 110.]])

In [28]:
np.dot(np.dot(np.linalg.inv(np.dot(zp1, zp1.T)), zp1), ks.T)

array([[444.17735732],
       [  2.62053888]])

Без интерсепт

In [24]:
zp2 = zp.reshape(1, len(zp))
ks = ks.reshape(1, len(ks))
d=np.dot(np.dot(np.linalg.inv(np.dot(zp2, zp2.T)), zp2), ks.T)
d

array([[5.88982042]])

In [25]:
mse1 = np.sum(((0 + 5.88982042 * zp2) - ks) ** 2 / 10)
mse1

56516.85841571942

In [26]:
def mse2(w1, y=ks, X=zp2, n=10):
    return np.sum((w1 * X - y) ** 2) / n
mse2(5.88982042)

56516.85841571943

2.Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [30]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
alpha = 1e-6
w1 = 0.1

def mse_(w1, y=ks, X=zp, n=10):
    return np.sum((w1 * X - y) ** 2) / n

In [31]:
for i in range(1000):
    fp = (1 / 10) * np.sum(2 * (w1 * zp - ks) * zp)
    w1 -= alpha * fp
    if i % 100 == 0:
        print(f'iteration: {i}, w1 : {w1}, mse: {mse_(w1) }')

iteration: 0, w1 : 0.25952808000000005, mse: 493237.7212546963
iteration: 100, w1 : 5.54537842245223, mse: 58151.31823171113
iteration: 200, w1 : 5.868748638669329, mse: 56522.97550129376
iteration: 300, w1 : 5.888531320728348, mse: 56516.88130936019
iteration: 400, w1 : 5.8897415574471985, mse: 56516.85850140053
iteration: 500, w1 : 5.889815595583751, mse: 56516.858416040064
iteration: 600, w1 : 5.889820124983314, mse: 56516.85841572062
iteration: 700, w1 : 5.889820402076462, mse: 56516.85841571941
iteration: 800, w1 : 5.88982041902807, mse: 56516.8584157194
iteration: 900, w1 : 5.889820420065112, mse: 56516.85841571941


Lesson 8

1. Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [32]:
footballers = np.array([173, 175, 180, 178, 177, 185, 183, 182])
hockey_players = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
weightlifters = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

Cредний рост 

In [35]:
f_mean = footballers.mean()
h_mean = hockey_players.mean()
w_mean = weightlifters.mean()
fulllist = np.hstack((footballers,hockey_players, weightlifters))
full_mean = fulllist.mean()
f_mean,h_mean,f_mean,full_mean

(179.125, 178.66666666666666, 179.125, 176.46428571428572)

In [41]:
full_s2 = np.sum((fulllist - full_mean) ** 2)
s2f = (f_mean - full_mean) ** 2 * len(footballers) + (h_mean - full_mean) ** 2 * len(hockey_players) + (w_mean - full_mean) ** 2 * len(weightlifters)
s2_ost = np.sum((footballers - f_mean) ** 2) + np.sum((hockey_players - h_mean) ** 2) + np.sum((weightlifters - w_mean) ** 2)
full_s2,s2f,s2_ost

(830.9642857142854, 253.9074675324678, 577.0568181818182)

In [42]:
s2_ost + s2f

830.964285714286

Дисперсии

In [43]:
s2_general = full_s2 / (len(fulllist) - 1)
s2_factor = s2f / (3 - 1)
s2_residual = s2_ost / (len(fulllist) - 3)
s2_general,s2_factor,s2_residual



(30.776455026455015, 126.9537337662339, 23.08227272727273)

In [44]:
F_h = s2_factor / s2_residual
len1=len(fulllist)
F_h,len1

(5.500053450812598, 28)

In [45]:
alpha = 0.05
d_f1 = 3 - 1
d_f2 = len(fulllist) - 3
d_f1, d_f2

(2, 25)

In [46]:
F_kr = 3.4928


Так как F_kr < F_h следовательно отличия между выборками существенные