1.Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [11]:
import numpy as np
import pylab
import scipy.stats as stats
zp=np.array( [35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks=np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
cov1=np.mean(zp*ks)-np.mean(zp)*np.mean(ks)
stdzp=np.std(zp,ddof=0)
stdks=np.std(ks,ddof=0)
cov2=np.cov(zp,ks,ddof=0)
cor1=np.corrcoef(zp,ks)
cor2=cov2/(stdzp*stdks)
cov1,cov2,cor1,cor2

(9157.839999999997,
 array([[ 3494.64,  9157.84],
        [ 9157.84, 30468.89]]),
 array([[1.        , 0.88749009],
        [0.88749009, 1.        ]]),
 array([[0.33866702, 0.88749009],
        [0.88749009, 2.95275283]]))

2.Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [21]:
iq=np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
a=0.05
Mx=np.mean(iq)
Dx=np.var(iq)
std=np.std(iq,ddof=1)
leniq=len(iq)
Tt=2.262
LeftBorder=Mx-Tt*std/(10**0.5)
RightBorder=Mx+Tt*std/(10**0.5)
LeftBorder,RightBorder

(110.55660776308164, 125.64339223691834)

3.Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с альфа =0,95

In [25]:
n=27
Dxgen=25
Stdgen=5
Stdx=Stdgen/(27**0.5)
Zt=1.96
Mx=174.2
LeftBorder=Mx-Zt*Stdx
RightBorder=Mx+Zt*Stdx
LeftBorder,RightBorder

(172.31398912064722, 176.08601087935276)